fixed bug in chd.sh

diff --git a/data/etc/rc/boot b/data/etc/rc/boot
--- a/data/etc/rc/boot
+++ b/data/etc/rc/boot
@@ -8,7 +8,11 @@ else
   if ! modprobe ipv4 &>/dev/null; then
     echo "failed";
   else
-    echo "ok";
+    if ! modprobe i350 &>/dev/null; then
+      echo "failed";
+    else
+      echo "ok";
+    fi
   fi
 fi
 
